version: "3"


services:
  master:
    restart: on-failure
    container_name: master
    hostname: master
    image: garkling/replicated-log-master:3.0.0

#    environment:

    ports:
      - "127.0.0.1:8080:${SERVER_PORT}"

  secondary:
    restart: on-failure
    container_name: secondary${NTH}
    hostname: ${SECONDARY_HOSTNAME:-secondary${NTH}}
    image: garkling/replicated-log-secondary:3.0.0

#    environment:


    ports:
      - "127.0.0.1:808${NTH}:${SERVER_PORT}"
