version: "3"


services:
  master:
    restart: on-failure
    container_name: master
    hostname: master
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_NAME: master
    image: replicated-log-master

    environment:
      RPC_PORT: 50051

    ports:
      - "127.0.0.1:8080:${SERVER_PORT}"

  secondary:
    restart: on-failure
    container_name: secondary${NTH}
    hostname: ${SECONDARY_HOSTNAME:-secondary${NTH}}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_NAME: secondary
    image: replicated-log-secondary

    environment:
      REPLICATION_DELAY_MS: 10000
      ORDER_DIFF_MULTIPLIER: 0.2
      ORDER_CORRECTION_TIME_LIMIT_MS: 60000

    ports:
      - "127.0.0.1:808${NTH}:${SERVER_PORT}"
