refresh_rate: 30 seconds

appenders:

  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {m}{n})}"
    filters:
      - kind: threshold
        level: info

root:
  appenders:
    - stdout